export const SERVICE_IDS = {
  REMINDER_ADD: "REMINDER_ADD",
  REMINDER_DAILIES: "REMINDER_DAILIES",
  REMINDER_MONTHLY: "REMINDER_MONTHLY",
  REMINDER_DELETE: "REMINDER_DELETE",
  USER_START: "USER_START",
};

export const CRON_JOB_IDS = {
  ALIVE_NOTIFY_ON_START: "ALIVE_NOTIFY_ON_START",
  REMINDER_DAILY: "REMINDER_DAILY",
};
