// The renderer's public surface: a stage to boot and the pieces it is built from.
export type { GameStage } from "./stage";
export { createGameStage } from "./stage";
export { GameRenderer } from "./renderer";
export type { RenderFlags } from "./flags";
export { DEFAULT_RENDER_FLAGS } from "./flags";
export type { ShadowCaster } from "./shadows";
export { castShadow, ShadowPool } from "./shadows";
export { Camera, DEFAULT_ZOOM, MAX_ZOOM, MIN_ZOOM } from "./camera";
export type { Layers } from "./layers";
export { createLayers } from "./layers";
export type { Ground } from "./ground";
export { buildGround } from "./ground";
export type { BakedTerrain } from "./terrain";
export { bakeTerrain } from "./terrain";
export type { WaterField, WaterSurface } from "./water";
export { buildWaterSurface } from "./water";
export { HOVER_STYLE, Marker, SELECTION_STYLE } from "./selection";
export type { Creature, Fills, Sheets } from "./textures";
export { Facing, fills, loadTextures, sheets, TREE_VARIANTS } from "./textures";
