/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import org.kodein.di.DI
import org.kodein.di.bindProvider

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

interface Random {
    fun get(): Int
}

class SecureRandom : Random {
    override fun get(): Int {
        return 1231;
    }
}

fun main() {
    println(App().greeting)

    val kodein = DI {
        bindProvider<Random> { SecureRandom() }
    }

    val instance: Random = kodein.direct.instance();

    println(instance.get())
}
